### ISSUE TITLE
解不了，直接报错了

### ISSUE THREAD

**Issue by FirstStepzz** [neil-wu/SwiftDump#2]
MachO1 :  [1]    3119 segmentation fault
MachO2:  [1]    3153 illegal hardware instruction  /Users/username/Project/Potatso/Tools/SwiftDump

**Comment by neil-wu** [comment]
Sorry,  I can read nothing with the information you provided. 
You can clone the repo and build by yourself. If you find a bug, any PR is welcome.

**Comment by neil-wu** [comment]
Please try the [latest release v1.0.1 ](https://github.com/neil-wu/SwiftDump/releases/tag/v1.0.1)
