### ISSUE TITLE
如何获取字串？

### ISSUE THREAD

**Issue by League2EB** [neil-wu/SwiftDump#3]
您好，感谢您的贡献

请原谅新手的我可能询问了比较低级的问题

如图，使用您的工具dump出来之后，我该怎么利用Hopper工具获取字串？

我想寻找的字串写在extension enum里头。

十分感谢您的答复。

![貼上的影像_2022_2_12_上午4_27.png](https://s2.loli.net/2022/02/12/KOJcZWtMs7r8uRz.png)

**Comment by neil-wu** [comment]
如果只是获取一个macho的所有字符串，可以使用strings命令： `strings XXX`。本项目目前解析不了struct里的默认字符串值。
